# Generated by Django 4.1.5 on 2023-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inserir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome:')),
                ('sobrenome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome:')),
                ('sexo', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='M', max_length=1)),
                ('altura', models.CharField(max_length=20, null=True)),
                ('peso', models.CharField(max_length=20, null=True)),
                ('nascimento', models.DateField(null=True)),
                ('bairro', models.CharField(max_length=150, null=True)),
                ('cidade', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('numero', models.CharField(max_length=30, null=True, verbose_name='nome')),
            ],
        ),
    ]
